# Generated by Django 6.0.6 on 2026-07-08 05:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('watering_interval', models.IntegerField(blank=True, help_text='Days between watering', null=True)),
                ('last_watered_on', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'plants',
            },
        ),
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('health_status', models.CharField(choices=[('Healthy', 'Healthy'), ('Wilting', 'Wilting'), ('Recovering', 'Recovering')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(db_column='plant_id', on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='accounts.plant')),
            ],
            options={
                'db_table': 'health_logs',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('owner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='owner',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='accounts.profile'),
        ),
        migrations.CreateModel(
            name='WateringLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('watered_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(db_column='plant_id', on_delete=django.db.models.deletion.CASCADE, related_name='watering_logs', to='accounts.plant')),
            ],
            options={
                'db_table': 'watering_logs',
            },
        ),
    ]
