# Generated by Django 6.0.6 on 2026-07-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthlog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='health_photos/'),
        ),
        migrations.AddField(
            model_name='plant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='plant_photos/'),
        ),
    ]
